name: flutter_paystack_client
description: Flutter Paystack payment plugin with support for Web, Android and iOS
version: 0.1.2
homepage: https://github.com/djade007/flutter_paystack_client

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  js: ^0.6.4
  flutter_paystack:
    git:
      url: https://github.com/theoaks/flutter_paystack.git

dev_dependencies:
  flutter_test:
    sdk: flutter
