name: flutter_theoaks_paystack_client
description: Flutter Paystack payment plugin with support for Web, Android and iOS. Forked from https://github.com/djade007/flutter_paystack_client
version: 0.1.3
homepage: https://github.com/thoaks/flutter_theoaks_paystack_client

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  js: ^0.6.4
  flutter_theoaks_paystack: ^1.0.5+4

dev_dependencies:
  flutter_test:
    sdk: flutter
